"""
Context compressor for AgentLoop.

When conversation history grows too long, compress older messages into a
concise summary. The summary is generated by the same LLM provider, then
injected as a system-level context note. Recent messages are kept intact
so the agent still has immediate conversational context.

Also persists summaries to TASK.md for cross-session memory.
"""
import json
import logging

from agent.providers.base import Done, LLMProvider, TextDelta

logger = logging.getLogger(__name__)

# ── Tunables ──────────────────────────────────────────────────────────────

# Rough chars-per-token estimate (conservative for CJK + English mix)
CHARS_PER_TOKEN = 3

# When estimated token count exceeds this, trigger compression
TOKEN_THRESHOLD = 12000

# Number of recent messages to keep verbatim (not compressed)
KEEP_RECENT = 6

# System prompt for the summarizer call
SUMMARIZER_PROMPT = """\
You are a conversation summarizer for OpenPlotAgent, a chart-generation tool.

Summarize the following conversation history into a compact paragraph.
Focus on:
1. What data the user has (file names, columns, shape)
2. What chart was created (type, key design decisions)
3. What modifications were requested and applied
4. Any user preferences mentioned (colors, fonts, styles, journal requirements)
5. Any errors encountered and how they were resolved

Be concise — aim for 150-300 words. Write in English.
Do NOT include tool call details or raw JSON. Only capture the semantic content.
"""


def _estimate_tokens(messages: list[dict]) -> int:
    """Rough token estimate from message content length."""
    total_chars = 0
    for msg in messages:
        content = msg.get("content", "")
        if isinstance(content, str):
            total_chars += len(content)
        elif isinstance(content, list):
            # Anthropic-style content blocks
            for block in content:
                if isinstance(block, dict):
                    total_chars += len(str(block.get("text", "")))
                    total_chars += len(str(block.get("content", "")))
        total_chars += 10  # role overhead
    return total_chars // CHARS_PER_TOKEN


def _messages_to_text(messages: list[dict]) -> str:
    """Flatten messages into readable text for the summarizer."""
    lines = []
    for msg in messages:
        role = msg.get("role", "?")
        content = msg.get("content", "")
        if isinstance(content, list):
            # Anthropic content blocks — extract text parts only
            parts = []
            for block in content:
                if isinstance(block, dict):
                    if block.get("type") == "text":
                        parts.append(block["text"])
                    elif block.get("type") == "tool_use":
                        parts.append(f"[tool_call: {block.get('name', '?')}]")
                    elif block.get("type") == "tool_result":
                        # Truncate tool results heavily
                        raw = str(block.get("content", ""))
                        parts.append(f"[tool_result: {raw[:200]}]")
            content = " ".join(parts)
        if not content:
            continue
        # Truncate very long individual messages
        if len(content) > 1500:
            content = content[:1500] + "..."
        lines.append(f"[{role}] {content}")
    return "\n".join(lines)


async def _call_summarizer(provider: LLMProvider, text: str) -> str:
    """Use the LLM to produce a summary."""
    messages = [
        {"role": "system", "content": SUMMARIZER_PROMPT},
        {"role": "user", "content": f"Conversation to summarize:\n\n{text}"},
    ]
    result_text = ""
    try:
        async for event in provider.chat(messages, tools=[]):
            if isinstance(event, TextDelta):
                # Strip any <think> tags from summary output
                result_text += event.content
            elif isinstance(event, Done):
                break
    except Exception as e:
        logger.warning("Summarizer call failed: %s", e)
        # Fallback: crude truncation
        return text[:800] + "\n[...conversation truncated...]"

    # Strip thinking tags if present (Qwen3)
    import re
    result_text = re.sub(r"<think>.*?</think>", "", result_text, flags=re.DOTALL)
    return result_text.strip()


async def maybe_compress(
    history: list[dict],
    provider: LLMProvider,
    task_md_path=None,
) -> list[dict]:
    """
    If history is long enough, compress older messages into a summary.

    Returns the (possibly shortened) history list.
    Also appends the summary to TASK.md if the path is provided.
    """
    estimated = _estimate_tokens(history)
    if estimated < TOKEN_THRESHOLD:
        return history  # No compression needed

    if len(history) <= KEEP_RECENT + 2:
        return history  # Too few messages to compress

    logger.info(
        "Context compression triggered: ~%d tokens, %d messages",
        estimated, len(history),
    )

    # Split: old messages to compress, recent to keep
    old_messages = history[:-KEEP_RECENT]
    recent_messages = history[-KEEP_RECENT:]

    # Check if there's already a summary at the start
    existing_summary = ""
    if old_messages and old_messages[0].get("role") == "system":
        existing_summary = old_messages[0]["content"]
        old_messages = old_messages[1:]

    # Build text to summarize
    text_to_summarize = ""
    if existing_summary:
        text_to_summarize = f"[Previous summary]\n{existing_summary}\n\n"
    text_to_summarize += _messages_to_text(old_messages)

    # Call summarizer
    summary = await _call_summarizer(provider, text_to_summarize)

    logger.info(
        "Compressed %d old messages into %d-char summary",
        len(old_messages), len(summary),
    )

    # Write summary to TASK.md for persistence
    if task_md_path:
        try:
            from pathlib import Path
            md_path = Path(task_md_path)
            md_path.parent.mkdir(parents=True, exist_ok=True)
            existing = md_path.read_text() if md_path.exists() else ""
            # Append under a section header
            separator = "\n\n---\n\n## Conversation Summary (auto-generated)\n\n"
            # Replace old summary section if present
            if "## Conversation Summary (auto-generated)" in existing:
                idx = existing.index("## Conversation Summary (auto-generated)")
                existing = existing[:idx - len("\n\n---\n\n")]
            md_path.write_text(existing + separator + summary + "\n")
        except Exception as e:
            logger.warning("Failed to write summary to TASK.md: %s", e)

    # Build compressed history: summary note + recent messages
    compressed = [
        {
            "role": "user",
            "content": (
                f"[CONTEXT SUMMARY — compressed from earlier conversation]\n\n"
                f"{summary}\n\n"
                f"[End of summary. The conversation continues below.]"
            ),
        },
        {
            "role": "assistant",
            "content": "Understood. I have the context from our earlier conversation. Let me continue from where we left off.",
        },
    ] + recent_messages

    new_estimated = _estimate_tokens(compressed)
    logger.info(
        "Context compressed: %d → %d messages, ~%d → ~%d tokens",
        len(history), len(compressed), estimated, new_estimated,
    )

    return compressed
